[package]
name = "pjsh_builtins"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }

pjsh_core = { path = "../pjsh_core" }

[dev-dependencies]
tempfile = "3.2.0"
