[package]
name = "pjsh_builtins"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
dirs = "4.0"
parking_lot = {version = "0.11", features = ["deadlock_detection"] }

pjsh_core = { path = "../pjsh_core" }
