[package]
name = "pjsh"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-rc.5", features = ["cargo", "derive"] }
dirs = "4.0"
lazy_static = "1.4.0"
regex = "1"
rustyline = "9.0"
rustyline-derive = "0.6"
sysinfo = "0.22.2"

pjsh_ast = { path = "../pjsh_ast" }
pjsh_builtins = { path = "../pjsh_builtins" }
pjsh_core = { path = "../pjsh_core" }
pjsh_exec = { path = "../pjsh_exec" }
pjsh_parse = { path = "../pjsh_parse" }
