[package]
name = "pjsh_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Core library for PJSH."

[dependencies]
parking_lot = {version = "0.12.1", features = ["deadlock_detection"] }

pjsh_ast = { path = "../pjsh_ast" }
